version: "3.9"

x-variaveis-comuns: &variaveis-comuns
  LANG: pt_BR.UTF-8
  LANGUAGE: pt_BR:pt
  LC_ALL: pt_BR.UTF-8
  TZ: America/Sao_Paulo

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: healthcore
    ports:
      - "5433:5432"
    volumes:
      - healthcore_dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 5
    networks: [app-network]

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    environment:
      <<: *variaveis-comuns
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      postgres:
        condition: service_healthy
    networks: [app-network]

volumes:
  healthcore_dbdata:

networks:
  app-network:
    name: app-network
    driver: bridge
