version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-filazero
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: filazero
    ports:
      - "5432:5432"
    volumes:
      - filazero_dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 15s
      retries: 3

volumes:
  filazero_dbdata: