version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: container_postgres_filazero
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: filazero
    ports:
      - "5433:5432"
    volumes:
      - filazero_dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 3
    networks:
      - app-network

  app-filazero:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-filazero
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LANG=pt_BR.UTF-8
      - LANGUAGE=pt_BR:pt
      - LC_ALL=pt_BR.UTF-8
      - JAVA_TOOL_OPTIONS= "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  filazero_dbdata:

networks:
  app-network: